# Generated by Django 2.2.10 on 2020-06-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['iswc'], name='music_music_iswc_d433f5_idx'),
        ),
    ]
