# Generated by Django 2.2.10 on 2020-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200618_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='iswc',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
