# Generated by Django 2.2.10 on 2020-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200619_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='contributors',
            field=models.CharField(max_length=250),
        ),
    ]
